# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./_gh_pages
host:           0.0.0.0
port:           9001
baseurl:        ""
url:            "http://localhost/9001"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - nuget/
  - scss/
  - vendor/
  - CODE_OF_CONDUCT.md
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - sache.json
  - twbsconfig.yml

# Social
title:              BeeGrid
description:        "A mini CSS microframework to build various types of grids thanks to a twelve column system, five default responsive tiers, Sass variables and mixins, and dozens of predefined classes to organize your content."
twitter:            beegrid
authors:            "Davide D'Antonio"

# Custom variables
current_version:      1.0.0-beta
docs_version:         1.0
repo:                 "https://github.com/davidedantonio/bee-grid.git"

download:
  source:           ""
  dist:             ""

include: ["_pages"]
