# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./docs
host:           0.0.0.0
port:           9001
baseurl:        "https://davidedantonio.github.io/bee-grid"
url:            "http://localhost/9001"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - scss/
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md

# Social
title:              BeeGrid
description:        "A microframework based on CSS Grid Layout to build various types of grids thanks to a twelve column system, five default responsive tiers, Sass variables and mixins, and dozens of predefined classes to organize your content."
twitter:            beegrid
authors:            "Davide D'Antonio"

# Custom variables
current_version:      1.0.0-rc.1
docs_version:         1.0
repo:                 "https://github.com/davidedantonio/bee-grid.git"
github:               "https://github.com/davidedantonio/bee-grid"
twitter:              "https://twitter.com/davidedantonio"

download:
  source:           "https://github.com/davidedantonio/bee-grid/archive/master.zip"
  dist:             "https://github.com/davidedantonio/bee-grid/archive/v1.0.0-rc-1.zip"
